### ISSUE TITLE
Informant does not speak

### ISSUE THREAD

**Issue by Baret** [Baret/arma3missions#1]
There is no local chat when talking to the informant.

**Comment by Loomie** [comment]
Works in single player. In MP started from the editor an error message is shown
```
Error in expression <createMarkerLocal ["mkr_closest_enemy", >
  Error position: <createMarkerLocal ["mkr_closest_enemy", >
  Error 0 elements provided, 3 expected
```
Problem was, that a private variable was given to the anonymous function given to remoteExecCall. The value was just not visible.

Also the chat is shown immediately, instead of waiting till the audio has stopped. So the chat seems to be visible on the hosting computer.

**Comment by Loomie** [comment]
Commit 37b0b1eb4e9233adfad3439b1bfa527cbb2fe37b fixes #1

**Comment by Loomie** [comment]
The problem still occurs on a dedicated server. Maybe because only [defined](https://community.bistudio.com/wiki/Arma_3_Remote_Execution#Security) commands can be called by remoteExec?

**Comment by Loomie** [comment]
Error in players log when playing on dedicated server:
```
 8:21:46 Error in expression <informant removeEventHandler ["killed", informantKilledEventIndex];
["task_infor>
 8:21:46   Error position: <informantKilledEventIndex];
["task_infor>
 8:21:46   Error Undefined variable in expression: informantkilledeventindex
```
Seems that the eventHandler variable cannot be used for the player executing the action. This has to be done where the event handler was registered.

But the next command (finish task) is executed anyway. So that is not the chat problem.
